#  ------------------------------------------------------------
#  |                      RealChat plugin                     |
#  |                                                          |
#  |           Author : huda0209                              |
#  |           Depend : LunaChat                              |
#  |   GitHub : https://github.com/AzisabaNetwork/RealChat    |
#  |                     ran by paper 1.13                    |
#  ------------------------------------------------------------


PluginMode: true

CanChatRange: 10
NoPlayerChatRangeError: true